### PR TITLE
Updated EmulationStation

### LINKED ISSUE #39: Retroachivements option in Settings not works
### Knulli build version

20240530 

### Your architecture

RG35XX PLUS

### Issue description

Retroachivements login works. Also it works in games without any problem. But when I wanted to see my achivements from Settings menu, it gives error every time.

### Detailed reproduction steps

- Login Retroachivements
- Try to run Retroachivements from Settings

### Details of any attempts to fix this yourself

Removed my Retroachivements account and re-enter again.
Made a clean install.

### Details of any modifications you have made to Knulli.

-

### Logs and data

_No response_

### PR DESCRIPTION
**Pull request by bladeoner**
- Fixed Retroachievements
- Video Mode (resolution) is now under System Settings rather than under Frontend Developers

I have tested the changes on my device, they are working.

This will fix #39

### CODE REVIEW

**Comment by HoroTW** [comment]
Hey @bladeoner,
I built a version with your PR and unfortunately issue #39 is not fixed for me, I still get a 419 (video mode is now under system settings, so I think it got built the way it should)

screenshot-2024-07-25_19h3651

Did you change anything else that was not in this PR?
Can you confirm that this is actually working for you?

Sorry if I just missed something ^^'.

**Comment by bladeoner** [comment]
Hi @HoroTW ,

I can confirm it is working for me. Today, I did a new build using the latest source, and it works.

Make sure you are compiling a clean build and that you create the keys.txt file containing the Cheevos API key and your username in the following format:
CHEEVOS_DEV_LOGIN=z=RETROACHIEVEMENTSUSERNAME&y=APIKEYID

You can retrieve your API key using the following url: https://retroachievements.org/controlpanel.php

**Comment by HoroTW** [comment]
Ah, I see, that's what I didn't know ^^
I didn't know about this file, what source of info did I miss? (I didn't read about it in the batocera documentation or ours, and the user interface didn't suggest it either)

**Comment by bladeoner** [comment]
I think it is not somewhere described, but if you don't define this and the other values the retro achievements and scraper sources are not build.

**Comment by HoroTW** [comment]
Thank you very much!
after looking through the make/CMake files and the EmulationStation code, I now understand how it all works together 😊.

**Pull request merged**
