### PR TITLE
include a bash script to change the device more easily

### PR DESCRIPTION
**Pull request by ajmandourah**
just a simple sed based bash script.

### CODE REVIEW

**Comment by bladeoner** [comment]
@ajmandourah is it possible to add the option to add multiple devices?

**Comment by ajmandourah** [comment]
Unfortunately not. Buildroot is quite limited in that sense.
You can though build one, change. And build the other on top. This will only generate the images as the devices are quite similar.

**Comment by bladeoner** [comment]
Thank you for your reponse, I understand.

What I do now, I changed the following, then both will be as you said build on top of the other:
Old: default "allwinner/h700/rg28xx" if BR2_PACKAGE_BATOCERA_TARGET_H700
New: default "allwinner/h700/rg35xx-h allwinner/h700/rg35xx-sp" if BR2_PACKAGE_BATOCERA_TARGET_H700

But I saw in your script that you update more files.

I will follow your approach, and change the device using the script.

**Comment by ajmandourah** [comment]
there are few other changes that you need to change in addition to the change you made in batocera-system config.ini.
mainly in the batocera-h700 board in configs folder.
these are the fsoverlay which handle specefic files which will be copied over the rootfs. these are important as some device require specefic configs. 
lastely is the patches. 

one thing i did not add is the kernal Kconfig as we are using the anbernic kernel and it wont matter

**Comment by bladeoner** [comment]
Thank you for your explanation, I will proceed using your script.

**Comment by bladeoner** [comment]
@ajmandourah just an update, your script works really good, thank you.

**Pull request merged**
